# Generated by Django 5.2.17 on 2026-09-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showdown_id', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=64)),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('short_desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '특성',
                'verbose_name_plural': '특성',
                'db_table': 'ability',
            },
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('name_ko', models.CharField(max_length=16)),
                ('plus_stat', models.CharField(blank=True, max_length=3)),
                ('minus_stat', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'verbose_name': '성격',
                'verbose_name_plural': '성격',
                'db_table': 'nature',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showdown_id', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=64)),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('num', models.IntegerField()),
                ('base_species', models.CharField(max_length=64)),
                ('forme', models.CharField(blank=True, max_length=32)),
                ('is_mega', models.BooleanField(default=False)),
                ('required_item', models.CharField(blank=True, max_length=48)),
                ('type1', models.CharField(max_length=16)),
                ('type2', models.CharField(blank=True, max_length=16)),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField(db_column='def')),
                ('spa', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('spe', models.IntegerField()),
                ('bst', models.IntegerField()),
                ('weight_kg', models.FloatField()),
            ],
            options={
                'verbose_name': '포켓몬',
                'verbose_name_plural': '포켓몬',
                'db_table': 'pokemon',
                'ordering': ['num', 'showdown_id'],
            },
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('showdown_mod', models.CharField(max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '레귤레이션',
                'verbose_name_plural': '레귤레이션',
                'db_table': 'ruleset',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('0', '특성1'), ('1', '특성2'), ('H', '숨겨진 특성'), ('S', '특수')], max_length=1)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.ability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_slots', to='dex.pokemon')),
            ],
            options={
                'verbose_name': '포켓몬 특성',
                'verbose_name_plural': '포켓몬 특성',
                'db_table': 'pokemon_ability',
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='pokemon', through='dex.PokemonAbility', to='dex.ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.ruleset'),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showdown_id', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=64)),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(max_length=16)),
                ('category', models.CharField(max_length=16)),
                ('power', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('target', models.CharField(max_length=32)),
                ('flags', models.CharField(blank=True, max_length=255)),
                ('secondary_chance', models.IntegerField(blank=True, null=True)),
                ('short_desc', models.TextField(blank=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.ruleset')),
            ],
            options={
                'verbose_name': '기술',
                'verbose_name_plural': '기술',
                'db_table': 'move',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showdown_id', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=64)),
                ('name_ko', models.CharField(blank=True, max_length=64)),
                ('mega_from', models.CharField(blank=True, max_length=64)),
                ('mega_to', models.CharField(blank=True, max_length=64)),
                ('short_desc', models.TextField(blank=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.ruleset')),
            ],
            options={
                'verbose_name': '도구',
                'verbose_name_plural': '도구',
                'db_table': 'item',
            },
        ),
        migrations.AddField(
            model_name='ability',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dex.ruleset'),
        ),
        migrations.CreateModel(
            name='TypeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacking', models.CharField(max_length=16)),
                ('defending', models.CharField(max_length=16)),
                ('multiplier', models.FloatField()),
            ],
            options={
                'verbose_name': '타입 상성',
                'verbose_name_plural': '타입 상성',
                'db_table': 'type_chart',
                'constraints': [models.UniqueConstraint(fields=('attacking', 'defending'), name='type_chart_pair')],
            },
        ),
        migrations.CreateModel(
            name='Learnset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='dex.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnset', to='dex.pokemon')),
            ],
            options={
                'verbose_name': '배우는 기술',
                'verbose_name_plural': '배우는 기술',
                'db_table': 'learnset',
                'constraints': [models.UniqueConstraint(fields=('pokemon', 'move'), name='learnset_pokemon_move')],
            },
        ),
        migrations.AddConstraint(
            model_name='pokemonability',
            constraint=models.UniqueConstraint(fields=('pokemon', 'slot'), name='pokemon_ability_slot'),
        ),
        migrations.AddConstraint(
            model_name='pokemon',
            constraint=models.UniqueConstraint(fields=('ruleset', 'showdown_id'), name='pokemon_ruleset_sid'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(fields=('ruleset', 'showdown_id'), name='move_ruleset_sid'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('ruleset', 'showdown_id'), name='item_ruleset_sid'),
        ),
        migrations.AddConstraint(
            model_name='ability',
            constraint=models.UniqueConstraint(fields=('ruleset', 'showdown_id'), name='ability_ruleset_sid'),
        ),
    ]
