# Generated by Django 5.2.17 on 2026-09-29 07:57

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_key', models.CharField(db_index=True, max_length=48)),
                ('source', models.CharField(choices=[('tournament', '대회'), ('user', '사용자'), ('synthetic', '합성'), ('opgg_replica', 'OP.GG 레플리카 팀'), ('showdown_replay', 'Showdown 리플레이')], max_length=24)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('event', models.CharField(blank=True, max_length=128)),
                ('player', models.CharField(blank=True, max_length=64)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('', '-'), ('win', '승'), ('lose', '패')], max_length=8)),
                ('played_on', models.DateField(blank=True, null=True)),
                ('raw_paste', models.TextField(blank=True)),
                ('is_legal', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dex.ruleset')),
            ],
            options={
                'verbose_name': '파티',
                'verbose_name_plural': '파티',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='UsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_key', models.CharField(max_length=48)),
                ('pokemon_key', models.CharField(db_index=True, max_length=48)),
                ('source', models.CharField(max_length=32)),
                ('season', models.CharField(blank=True, max_length=16)),
                ('snapshot_date', models.DateField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('usage_pct', models.FloatField(blank=True, null=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dex.ruleset')),
            ],
            options={
                'verbose_name': '사용률',
                'verbose_name_plural': '사용률',
                'db_table': 'usage_stat',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UsageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('move', '기술'), ('item', '도구'), ('ability', '특성'), ('nature', '성격'), ('spread', 'SP 배분'), ('teammate', '동료')], max_length=16)),
                ('target_key', models.CharField(max_length=48)),
                ('pct', models.FloatField()),
                ('usage_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='meta.usagestat')),
            ],
            options={
                'verbose_name': '사용률 상세',
                'verbose_name_plural': '사용률 상세',
                'db_table': 'usage_detail',
                'ordering': ['-pct'],
            },
        ),
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_key', models.CharField(db_index=True, max_length=48)),
                ('item_key', models.CharField(blank=True, max_length=48)),
                ('ability_key', models.CharField(blank=True, max_length=48)),
                ('nature_key', models.CharField(blank=True, max_length=16)),
                ('sp_hp', models.PositiveSmallIntegerField(default=0)),
                ('sp_atk', models.PositiveSmallIntegerField(default=0)),
                ('sp_def', models.PositiveSmallIntegerField(default=0)),
                ('sp_spa', models.PositiveSmallIntegerField(default=0)),
                ('sp_spd', models.PositiveSmallIntegerField(default=0)),
                ('sp_spe', models.PositiveSmallIntegerField(default=0)),
                ('move1', models.CharField(blank=True, max_length=48)),
                ('move2', models.CharField(blank=True, max_length=48)),
                ('move3', models.CharField(blank=True, max_length=48)),
                ('move4', models.CharField(blank=True, max_length=48)),
                ('format_key', models.CharField(db_index=True, max_length=48)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('usage_pct', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(max_length=24)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dex.ruleset')),
            ],
            options={
                'verbose_name': '육성형',
                'verbose_name_plural': '육성형',
                'db_table': 'pokemon_set',
                'constraints': [models.CheckConstraint(condition=models.Q(('sp_hp__gte', 0), ('sp_hp__lte', 32)), name='pokemon_set_sp_hp_range'), models.CheckConstraint(condition=models.Q(('sp_atk__gte', 0), ('sp_atk__lte', 32)), name='pokemon_set_sp_atk_range'), models.CheckConstraint(condition=models.Q(('sp_def__gte', 0), ('sp_def__lte', 32)), name='pokemon_set_sp_def_range'), models.CheckConstraint(condition=models.Q(('sp_spa__gte', 0), ('sp_spa__lte', 32)), name='pokemon_set_sp_spa_range'), models.CheckConstraint(condition=models.Q(('sp_spd__gte', 0), ('sp_spd__lte', 32)), name='pokemon_set_sp_spd_range'), models.CheckConstraint(condition=models.Q(('sp_spe__gte', 0), ('sp_spe__lte', 32)), name='pokemon_set_sp_spe_range'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('sp_hp'), '+', models.F('sp_atk')), '+', models.F('sp_def')), '+', models.F('sp_spa')), '+', models.F('sp_spd')), '+', models.F('sp_spe')), 66), name='pokemon_set_sp_total')],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_key', models.CharField(db_index=True, max_length=48)),
                ('item_key', models.CharField(blank=True, max_length=48)),
                ('ability_key', models.CharField(blank=True, max_length=48)),
                ('nature_key', models.CharField(blank=True, max_length=16)),
                ('sp_hp', models.PositiveSmallIntegerField(default=0)),
                ('sp_atk', models.PositiveSmallIntegerField(default=0)),
                ('sp_def', models.PositiveSmallIntegerField(default=0)),
                ('sp_spa', models.PositiveSmallIntegerField(default=0)),
                ('sp_spd', models.PositiveSmallIntegerField(default=0)),
                ('sp_spe', models.PositiveSmallIntegerField(default=0)),
                ('move1', models.CharField(blank=True, max_length=48)),
                ('move2', models.CharField(blank=True, max_length=48)),
                ('move3', models.CharField(blank=True, max_length=48)),
                ('move4', models.CharField(blank=True, max_length=48)),
                ('slot', models.PositiveSmallIntegerField()),
                ('is_gimmick_user', models.BooleanField(default=False)),
                ('brought', models.BooleanField(blank=True, null=True)),
                ('lead', models.BooleanField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='meta.team')),
            ],
            options={
                'verbose_name': '파티 멤버',
                'verbose_name_plural': '파티 멤버',
                'db_table': 'team_member',
                'ordering': ['team', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('team', 'slot'), name='team_member_slot_unique'), models.CheckConstraint(condition=models.Q(('slot__gte', 1), ('slot__lte', 6)), name='team_member_slot_range'), models.CheckConstraint(condition=models.Q(('sp_hp__gte', 0), ('sp_hp__lte', 32)), name='team_member_sp_hp_range'), models.CheckConstraint(condition=models.Q(('sp_atk__gte', 0), ('sp_atk__lte', 32)), name='team_member_sp_atk_range'), models.CheckConstraint(condition=models.Q(('sp_def__gte', 0), ('sp_def__lte', 32)), name='team_member_sp_def_range'), models.CheckConstraint(condition=models.Q(('sp_spa__gte', 0), ('sp_spa__lte', 32)), name='team_member_sp_spa_range'), models.CheckConstraint(condition=models.Q(('sp_spd__gte', 0), ('sp_spd__lte', 32)), name='team_member_sp_spd_range'), models.CheckConstraint(condition=models.Q(('sp_spe__gte', 0), ('sp_spe__lte', 32)), name='team_member_sp_spe_range'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('sp_hp'), '+', models.F('sp_atk')), '+', models.F('sp_def')), '+', models.F('sp_spa')), '+', models.F('sp_spd')), '+', models.F('sp_spe')), 66), name='team_member_sp_total')],
            },
        ),
        migrations.AddConstraint(
            model_name='usagestat',
            constraint=models.UniqueConstraint(fields=('ruleset', 'format_key', 'pokemon_key', 'source', 'season', 'snapshot_date'), name='usage_stat_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='usagedetail',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['move', 'item', 'ability', 'nature', 'spread', 'teammate'])), name='usage_detail_kind'),
        ),
    ]
