# Generated by Django 5.2.17 on 2026-09-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagestat',
            name='prev_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
