# Generated by Django 5.2.17 on 2026-10-01 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0001_initial'),
        ('meta', '0002_usagestat_prev_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_key', models.CharField(max_length=48)),
                ('source', models.CharField(default='opgg', max_length=32)),
                ('season', models.CharField(blank=True, max_length=16)),
                ('captured_at', models.DateTimeField()),
                ('pokemon_key', models.CharField(db_index=True, max_length=48)),
                ('rank', models.IntegerField()),
                ('season_change', models.IntegerField(blank=True, null=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dex.ruleset')),
            ],
            options={
                'verbose_name': '순위 스냅샷',
                'verbose_name_plural': '순위 스냅샷',
                'db_table': 'rank_snapshot',
                'ordering': ['-captured_at', 'rank'],
                'indexes': [models.Index(fields=['format_key', 'source', 'captured_at'], name='rank_snapsh_format__b89f35_idx')],
                'constraints': [models.UniqueConstraint(fields=('format_key', 'source', 'captured_at', 'pokemon_key'), name='rank_snapshot_unique')],
            },
        ),
    ]
