# Generated by Django 5.2.17 on 2026-10-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_rank_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='sp_from',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='team',
            name='source',
            field=models.CharField(choices=[('tournament', '대회'), ('user', '사용자'), ('synthetic', '합성'), ('opgg_replica', 'OP.GG 레플리카 팀'), ('showdown_replay', 'Showdown 리플레이'), ('vgcpastes', 'VGCPastes 대회 팀')], max_length=24),
        ),
    ]
